src/Boards/Models/Board.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Boards.Models
{
    public class Board
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
    }
}

src/Boards/ViewModels/BoardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Boards.ViewModels
{
    public class BoardViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [StringLength(2048)]
        public string Description { get; set; }
    }
}

src/Boards/Controllers/Api/BoardController.cs
using AutoMapper;
using Boards.Models;
using Boards.ViewModels;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace Boards.Controllers.Api
{
    [Authorize]
    [Route("api/boards")]
    public class BoardController : BoardsBaseController
    {
        private ILogger<BoardController> _logger;

        public BoardController(IBoardsRepository repository, ILogger<BoardController> logger) : base(repository)
        {
            _logger = logger;
        }

        [HttpGet("")]
        public JsonResult Get()
        {
            var boards = Mapper.Map<IEnumerable<BoardViewModel>>(_repository.GetAllUserBoards(User.Identity.Name));
            return Json(boards);
        }

        [HttpPost("")]
        public JsonResult Post([FromBody]BoardViewModel vm)
        {
            string serverErrorMessage = "There was a problem saving your new board. Please try again.";

            try
            {
                if (ModelState.IsValid)
                {
                    var newBoard = Mapper.Map<Board>(vm);
                    newBoard.UserName = User.Identity.Name;

                    // Save to DB
                    _logger.LogInformation("Attempting to save new board");
                    _repository.AddBoard(newBoard);

                    if (_repository.SaveAll())
                    {
                        _addDefaultCategory(newBoard);
                        _addDefaultPhases(newBoard);

                        if (_repository.SaveAll())
                        {
                            Response.StatusCode = (int)HttpStatusCode.Created;
                            return Json(Mapper.Map<Board, BoardViewModel>(newBoard));
                        }
                        else
                        {
                            _logger.LogError($"Board creation succeeded but there was an issue creating default categories or phases. BoardId: {newBoard.Id}");
                            throw new Exception("Board creation succeeded default category/phase creation failed.");
                        }
                    }
                }
            }

            catch (Exception ex)
            {
                _logger.LogError("Failed to save new board", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = serverErrorMessage });
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new { Message = serverErrorMessage, ModelState = ModelState });
        }

        [HttpDelete("{id}")]
        public JsonResult Delete(int id)
        {
            if (_repository.RemoveBoard(id, User.Identity.Name))
            {
                return Json(new { Message = "Success" });
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = "Failed" });
            }
        }

        [HttpPut("")]
        public JsonResult Put([FromBody] BoardViewModel vm)
        {
            string serverErrorMessage = "There was a problem updating your board. Please try again.";

            try
            {
                if (ModelState.IsValid)
                {
                    var board = Mapper.Map<Board>(vm);
                    var username = User.Identity.Name;

                    // Save to DB
                    _logger.LogInformation($"Attemping to update board \"{vm.Name}\" (ID: {vm.Id})");
                    _repository.UpdateBoard(board, username);

                    if (_repository.SaveAll())
                    {
                        Response.StatusCode = (int)HttpStatusCode.OK;
                        return Json(Mapper.Map<Board, BoardViewModel>(board));
                    }
                }
            }

            catch (Exception ex)
            {
                _logger.LogError("Failed to update board.", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = serverErrorMessage });
            }

            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new { Message = serverErrorMessage, ModelState = ModelState });
        }

        [HttpGet("{id}")]
        public JsonResult GetBoardData(int id)
        {
            try
            {
                _assertUserAccessToBoard(id);
                var boardData = _repository.GetBoardData(id);
                return Json(boardData);
            }

            catch(Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = "Failed to get board data", exception = ex.Message });
            }
        }

        private void _addDefaultCategory(Board newBoard)
        {
            var newCategory = new Category()
            {
                Name = "Task",
                BoardId = newBoard.Id,
                ColorCode = 1
            };

            _repository.AddCategory(newCategory);
        }

        private void _addDefaultPhases(Board newBoard)
        {
            string[] defaultPhaseNames = { "Backlog", "In Progress", "Done" };
            int order = 1;

            foreach (string phaseName in defaultPhaseNames)
            {
                Phase newPhase = new Phase()
                {
                    Name = phaseName,
                    Order = order++,
                    BoardId = newBoard.Id
                };

                _repository.AddPhase(newPhase);
            }
        }
    }
}

src/Boards/Controllers/Web/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Boards.Models;
using Microsoft.AspNet.Authorization;
using System.Net;

namespace Boards.Controllers.Web
{
    [Authorize]
    [Route("boards")]
    public class BoardsController : BoardsBaseController
    {
        public BoardsController(IBoardsRepository repository) : base(repository)
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("{id}/categories")]
        public IActionResult Categories()
        {
            try
            {
                _assertUserAccessToBoard();

                Board thisBoard = _getCurrentBoard();

                ViewBag.BoardName = thisBoard.Name;
                ViewBag.BoardId = thisBoard.Id;
                return View();
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return RedirectToAction("PageNotFound", "App");
            }
        }

        [HttpGet("{id}")]
        public IActionResult Board()
        {
            try
            {
                _assertUserAccessToBoard();

                Board thisBoard = _getCurrentBoard();

                ViewBag.BoardName = thisBoard.Name;
                ViewBag.BoardId = thisBoard.Id;
                ViewBag.BoardDescription = thisBoard.Description;
                return View();
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return RedirectToAction("PageNotFound", "App");
            }
        }

        private Board _getCurrentBoard()
        {
            int boardId = int.Parse((string)RouteData.Values["id"]);
            return _repository.GetBoardForUser(boardId, User.Identity.Name);
        }
    }
}

src/Boards/Views/Boards/Board.cshtml
@{
    ViewBag.Title = ViewBag.BoardName;
}

<div class="wrap">
    <div id="board-info">
        <h1>@ViewBag.BoardName</h1>
        <p>@ViewBag.BoardDescription</p>
    </div>
    <single-board category-url="@Url.Action("Categories", "Boards", new { id = ViewBag.BoardId })" board-id="@ViewBag.BoardId">
        <div id="board">
            <p class="message">
                <i class="fa fa-spinner fa-spin"></i> Loading tasks
            </p>
        </div>
    </single-board>
</div>

src/Boards/Views/Boards/Categories.cshtml
@{
    ViewBag.Title = ViewBag.BoardName;
}

<div ng-controller="CategoriesCtrl as categoriesCtrl">
    <div class="wrap narrow" id="categories-list-page">
        <div class="gencon">
            <h1>@ViewBag.BoardName Categories</h1>
            <a href="@Url.Action("Board", "Boards", new { id = ViewBag.BoardId })" class="back">Back to @ViewBag.BoardName</a>
            <div id="list-pane">
                <button ng-click="categoriesCtrl.newCategoryClicked()"><i class="fa fa-plus"></i> New Category</button>
                <categories-list board-id="@ViewBag.BoardId">
                    <p class="message">
                        <em><i class="fa fa-spinner fa-spin"></i> Loading Categories</em>
                    </p>
                </categories-list>
            </div>
        </div>
    </div>

    <div categories-modal
         modal-title="categoriesCtrl.modalTitle"
         modal-active="categoriesCtrl.modalActive"
         modal-method="categoriesCtrl.modalMethod"
         modal-color-code="categoriesCtrl.modalColorCode"
         board-id="@ViewBag.BoardId"
         ng-class="['modal', {'active': categoriesCtrl.modalActive}]">
    </div>
</div>

src/Boards/Views/Boards/Index.cshtml
@{
    ViewBag.Title = $"{User.Identity.Name}'s Boards";
}
<div ng-controller="BoardsCtrl as boardsCtrl">
    <div class="wrap narrow">
        <div class="gencon">
            <h1>Hello, @User.Identity.Name</h1>
            <div id="list-pane">
                <h2>My Boards</h2>
                <button ng-click="boardsCtrl.newBoardClicked()"><i class="fa fa-plus"></i> New Board</button>
                <boards-list>
                    <p class="message">
                        <em><i class="fa fa-spinner fa-spin"></i> Loading Boards</em>
                    </p>
                </boards-list>
            </div>
        </div>
    </div>

    <div boards-modal
        modal-title="boardsCtrl.modalTitle"
        modal-active="boardsCtrl.modalActive"
        modal-method="boardsCtrl.modalMethod"
        ng-class="['modal', {'active':boardsCtrl.modalActive}]">
    </div>
</div>